const types = {
    ENABLE_LOADER: 'ENABLE_LOADER',
    DISABLE_LOADER: 'DISABLE_LOADER',
    ADD_TODO: 'ADD_TODO',
    TODO: 'TODO',
    TODO_PENDING: 'TODOS_PENDING',
    TODO_DONE: 'TODO_DONE',
    TODO_REJECTED: 'TODO_REJECTED',
    ADD_USER: 'ADD_USER',
    USERS: 'USERS',
    USERS_PENDING: 'USERS_PENDING',
    USERS_DONE: 'USERS_DONE',
    USERS_REJECTED: 'USERS_REJECTED',
    POSTS: 'POSTS',
    POSTS_PENDING: 'POSTS_PENDING',
    POSTS_DONE: 'POSTS_DONE',
    POSTS_REJECTED: 'POSTS_REJECTED'
};

export default types;